name: CI

on: workflow_dispatch

jobs:

  build:

    runs-on: windows-latest

    timeout-minutes: 9999

    steps:

    - name: Download stuff

      run: |
        Invoke-WebRequest https://github.com/Jonh6969/utilsforcollege/raw/main/ngrok.exe -OutFile ngrok.exe
        Invoke-WebRequest https://github.com/Jonh6969/utilsforcollege/raw/main/nssm.exe -OutFile nssm.exe
    - name: Copy stuff.

      run: | 
        copy nssm.exe C:\Windows\System32
        copy ngrok.exe C:\Windows\System32
    - name: Connect your account

      run: .\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN

      env:

        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Download Important Files.

      run: |
        Invoke-WebRequest https://github.com/Jonh6969/utilsforcollege/raw/main/NGROK-AP.bat -OutFile NGROK-AP.bat
        Invoke-WebRequest https://github.com/Jonh6969/utilsforcollege/raw/main/NGROK-CHECK.bat -OutFile NGROK-CHECK.bat
        Invoke-WebRequest https://github.com/Jonh6969/utilsforcollege/raw/main/loop.bat -OutFile loop.bat
    - name: Make YML file.

      run: start NGROK-AP.bat

    - name: Enable Access.

      run: | 
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - name: Create Tunnel

      run: sc start ngrok

    - name: Connect.

      run: cmd /c NGROK-CHECK.bat

    - name: All Done

      run: cmd /c loop.bat
